#!/bin/tcsh

#Created by Mark Shephard, August 2002

#This script opens, seaches, and replaces characters in files in order
#for the global double precision to work with the PGI compiler.

#Compiling in single precision does not have a problem

#Issue:

#In double precision: -fast -r8 -i8
#One get the errors like: 
#PGF90-S-0201-Illegal I/O specifier - OPENED (src/lblrtm.f: 621)
#PGF90-S-0201-Illegal I/O specifier - IOSTAT (src/lblrtm.f: 765)

#The following represents the code type which causes a problem:
#logical op
#INQUIRE (UNIT=13,OPENED=OP)
#OPEN(15,FILE='REJ1',STATUS='NEW',FORM='UNFORMATTED',
#     *        IOSTAT=iostat)
 
#If IOSTAT is explicitly set to integer*4 and the LOGICAL values to logical*4 
#in code and compile with the global double precision then the code compiles
#properly.

#Apparent "bug" in the PGI linux compilier with the OPEN and INQUIRE statements 
#(part of the fortran language) is that their arguments are always fixed as long, 
#which on an x86 processor is integer*4.

##Search and replace

cd src

foreach i (`ls *.f`)
echo $i
#replace 
cat $i | sed 's/c%%%%%LINUX_PGI90 (-i8)%%%%%//g' > $i.tmp
cat $i.tmp | sed 's/ LOGICAL / LOGICAL*4 /g' > $i:r_linux.f
\rm $i.tmp
end

\rm util_aix_linux.f  util_dos_linux.f 
\rm util_sgi_linux.f util_linux_pgi_linux.f util_sun_linux.f
\rm util_alpha_linux.f  util_cray_linux.f util_hp_linux.f 
\rm solar_linux.f contnm_linux.f testmm_linux.f lbldum_linux.f

cd ../

make -f makefiles/makelbl.pgi_linux_f90_dbl

cd src

\rm *_linux.f
